version: 2
jobs:
  unit_tests:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache

      - run:
          name: Unit Tests
          command: npm run test:unit --coverage && cat ./coverage/lcov.info | codacy-coverage

  e2e_tests:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm

    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache

      - run:
          name: E2E Tests
          command: $(npm bin)/cypress run --record --key $CYPRESS_RECORD_KEY

  workflows:
    version: 2
    run-tests:
      steps:
        - unit_tests:
            filters:
              branches:
                only: master

        - e2e_tests:
            requires:
              - unit_tests
            filters:
              branches:
                only: master
